# Generated by Django 3.1.3 on 2022-01-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='join',
            new_name='KakaoFriend',
        ),
    ]
